alias cp-envoy="cp -v ~/digicod/envoy_modular_config/generated/envoy.yaml /etc/envoy"
alias restartctl="sudo systemctl restart"
alias startctl="sudo systemctl start"
alias stopctl="sudo systemctl stop"
alias statusctl="sudo systemctl status"
alias enablectl="sudo systemctl enable"
alias enablectl-now="sudo systemctl enable --now"