const endpoints = [
   'GetProduct',
   'GetBasket',
   'GetCategory',
   'GetBrand',
   'GetRegion',
   'GetCurrency',
   'GetUserProfile',
   'UpdateUserProfile',
   'GetOrder'
]

const urlendpoints = {
   GetProduct: { method: 'GET', url: '/getproduct' },
   GetBasket: { method: 'GET', url: '/getbasket' },
   GetCategory: { method: 'GET', url: '/getcategory' },
   GetBrand: { method: 'GET', url: '/getbrand' },
   GetRegion: { method: 'GET', url: '/getregion' },
   GetCurrency: { method: 'GET', url: '/getcurrency' },
   GetUserProfile: { method: 'GET', url: '/getuserprofile' },
   UpdateUserProfile: { method: 'PUT', url: '/updateuserprofile' },
   GetOrder: { method: 'GET', url: '/getorder' }
}

const endpoints2 = [
   'GetProduct',
   'GetBasket',
   'AddToBasket',
   'RemoveFromBasket',
   'UpdateBasketItem',
   'ClearBasket',
   'GetCategories',
   'GetBrands',
   'GetRegions',
   'SearchProducts',
   'GetProductDetails',
   'GetCurrency',
   'GetShippingOptions',
   'ApplyDiscountCode',
   'RemoveDiscountCode',
   'GetUserProfile',
   'UpdateUserProfile',
   'GetOrderHistory',
   'GetOrderDetails',
   'CreateOrder',
   'CancelOrder',
   'GetPaymentMethods',
   'ProcessPayment',
   'GetStockLevels',
   'GetProductReviews',
   'SubmitProductReview',
   'GetRelatedProducts',
   'GetFeaturedProducts',
   'GetNewArrivals',
   'GetBestSellers',
   'GetOnSaleProducts',
   'GetProductRecommendations',
   'GetRecentlyViewedProducts',
]