# Generated by Django 5.0.6 on 2024-06-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_alter_coinwallet_user_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='json'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Payment Provider'),
        ),
    ]
