# [program:product_prices_sinc]
# command=/home/dcback/venv/bin/python3 product_prices_sinc.py
# directory=/home/dcback/programs
# user=root
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/dcback/programs/debug.log


# [supervisord]
# logfile = /home/dcback/programs/supervisord.log
# logfile_maxbytes = 50MB
# logfile_backups=10
# loglevel = info
# pidfile = /home/dcback/programs/supervisord.pid
# nodaemon = true
# minfds = 1024
# minprocs = 200
# umask = 022
# user = root
# identifier = supervisor_product_prices_sinc
# directory = /tmp
# nocleanup = false
# childlogdir = /tmp
