# Generated by Django 4.2.23 on 2026-05-02 10:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('payment_method_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Payment method payment')),
                ('wallet_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Wallet payment')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Total price')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Final price')),
                ('process_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Processing fee')),
                ('addinfo', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional info')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending_payment', max_length=100, verbose_name='Order Status')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_currency', to='shop.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='accounts.customer', verbose_name='Customer')),
                ('fingprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_fingprint', to='shop.fingprint', verbose_name='FingPrint')),
                ('payment_method', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pay_method', to='shop.payment', verbose_name='Paymentmethod')),
                ('products', models.ManyToManyField(related_name='order_products', to='shop.product', verbose_name='Products')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
        ),
    ]
