# Generated by Django 3.2.13 on 2023-05-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_cartn_cproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartn',
            name='cproducts',
            field=models.JSONField(default={}, verbose_name='cproducts json'),
        ),
    ]
