# Generated by Django 3.2.13 on 2023-05-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_cartn_cproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='cart',
            name='ex_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='json',
            field=models.JSONField(default={}, verbose_name='json'),
        ),
        migrations.DeleteModel(
            name='Cartn',
        ),
    ]
