# Generated by Django 3.2.13 on 2023-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_alter_cart_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ex_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='Ex Rate'),
        ),
    ]
