# Generated by Django 3.2.13 on 2023-09-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_urltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
    ]
