# Generated by Django 3.2.13 on 2023-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_loginstatistic_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstatistic',
            name='json',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='json'),
        ),
    ]
