# Generated by Django 4.2.7 on 2024-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_alter_loginstatistic_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingeprint', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='FingerPrint')),
                ('json', models.JSONField(blank=True, null=True, verbose_name='json')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
