# Generated by Django 4.2.7 on 2024-01-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_fingprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fingprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_cart_order', to='eshop.fingprint', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingprint_cart', to='eshop.order', verbose_name='fingprint'),
        ),
    ]
