# Generated by Django 4.2.7 on 2024-03-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0020_alter_cart_fingprint_alter_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='producte',
            field=models.ManyToManyField(blank=True, related_name='cart', to='eshop.product'),
        ),
    ]
