# Generated by Django 4.2.7 on 2024-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0021_cart_producte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='producte',
            field=models.ManyToManyField(blank=True, related_name='cart', to='eshop.product', verbose_name='Producte'),
        ),
    ]
