# Generated by Django 4.2.7 on 2024-03-21 09:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0022_alter_cart_producte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='producte',
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('payment_method_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Payment method payment')),
                ('wallet_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Wallet payment')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Final price')),
                ('process_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Processing fee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.currency', verbose_name='Currency')),
                ('fingprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.fingprint', verbose_name='fingprint')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop.customer', verbose_name='Customer')),
                ('payment_method', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.payment', verbose_name='Paymentmethod')),
                ('payoption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.payoptions', verbose_name='Payoption')),
                ('products', models.ManyToManyField(blank=True, related_name='basket', to='eshop.product', verbose_name='Products')),
            ],
        ),
    ]
