# Generated by Django 4.2.7 on 2024-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0023_remove_cart_producte_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_products',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Basket Products'),
        ),
    ]
