# Generated by Django 4.2.7 on 2024-03-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0029_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_products',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Basket Products'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='basket', to='eshop.product', verbose_name='Products'),
        ),
    ]
