# Generated by Django 4.2.7 on 2024-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0030_alter_basket_basket_products_alter_basket_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='final_price',
            new_name='total',
        ),
        migrations.AddField(
            model_name='orders',
            name='process_fees',
            field=models.JSONField(default=dict, verbose_name='Process fees'),
        ),
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.JSONField(default=dict, verbose_name='Total Price'),
        ),
    ]
