# Generated by Django 4.2.7 on 2024-03-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0032_orders_pay_method_orders_pay_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='basket',
            name='addinfo',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional info'),
        ),
        migrations.AddField(
            model_name='basket',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.basket', verbose_name='Basket'),
            preserve_default=False,
        ),
    ]
