# Generated by Django 4.2.7 on 2024-03-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0033_remove_orders_customer_basket_addinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.basket', verbose_name='Basket'),
        ),
    ]
