# Generated by Django 4.2.23 on 2026-05-02 10:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('payment_method_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Payment method payment')),
                ('wallet_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Wallet payment')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Total price')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Final price')),
                ('process_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Processing fee')),
                ('addinfo', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional info')),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Qty')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cart Product Price')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total Price')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='shop.cart', verbose_name='Cart')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('base', models.BooleanField(default=False, verbose_name='Base')),
                ('longname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longname')),
                ('shortname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shortname')),
                ('sign', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sign')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=19, null=True, verbose_name='Min amount')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('image2', models.CharField(blank=True, max_length=255, null=True, verbose_name='image_svg')),
                ('svg', models.TextField(blank=True, null=True, verbose_name='Svg')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Html')),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='Price')),
                ('orig_price', models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='Exchange price')),
                ('fee_rate', models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='Fee rate %')),
                ('histori', models.BinaryField(blank=True, null=True, verbose_name='Histori')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['-type', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=30, null=True, verbose_name='Category')),
                ('jdata', models.JSONField(blank=True, null=True, verbose_name='jdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FingPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('fingprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='FingPrint')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('jdata', models.JSONField(blank=True, null=True, verbose_name='jdata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Suplier')),
                ('suplier_code', models.CharField(choices=[('PREPAIDFORGE', 'Prepaidforge')], max_length=50, verbose_name='suplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('suplier_order_id', models.CharField(max_length=255, verbose_name='PF order Reference')),
                ('orderid', models.CharField(max_length=255, verbose_name='Order ID')),
                ('code', models.CharField(max_length=500, verbose_name='Code')),
                ('serial', models.CharField(max_length=500, verbose_name='Serial')),
                ('downloadLink', models.CharField(default='', max_length=255, verbose_name='Download Link')),
                ('codeType', models.CharField(default='', max_length=100, verbose_name='codeType')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Cart')),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cartproduct', verbose_name='CartProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Price')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Profit %')),
                ('profit_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Profit fixed')),
                ('prurchase_price', models.DecimalField(decimal_places=2, default=False, max_digits=9, null=True, verbose_name='PF-Price')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(default=False, max_length=255, null=True, unique=True, verbose_name='Sku')),
                ('slug', models.SlugField(default=None, max_length=255, null=True, unique=True)),
                ('gtin', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='GTIN')),
                ('ean', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='EAN')),
                ('regions', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Regions')),
                ('suplier_product', models.JSONField(blank=True, default=dict, null=True, verbose_name='suplier_product')),
                ('value', models.CharField(default=None, max_length=255, verbose_name='Value')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('jsondata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional info')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.category')),
                ('suplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_suplier', to='shop.suplier')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('provider', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Payment Provider')),
                ('name', models.CharField(max_length=255, verbose_name='Payment Name')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fee_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Fee %')),
                ('fee_fix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Fee Fix')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('svg', models.TextField(blank=True, null=True, verbose_name='Svg')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Html')),
                ('json', models.JSONField(blank=True, default=dict, null=True, verbose_name='json')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('brands', models.ManyToManyField(blank=True, related_name='related_brand_payment', to='shop.brand', verbose_name='brands')),
                ('currencies', models.ManyToManyField(blank=True, related_name='related_pay_currencyes', to='shop.currency', verbose_name='currencies')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_codes',
            field=models.ManyToManyField(blank=True, related_name='related_cart_product', to='shop.productcode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_currency', to='shop.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer', to='accounts.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='fingprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_fingprint', to='shop.fingprint', verbose_name='FingPrint'),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_pay_method', to='shop.payment', verbose_name='Paymentmethod'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='basket', to='shop.product', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='shop.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='suplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_suplier', to='shop.suplier'),
        ),
    ]
