# Generated by Django 4.2.23 on 2026-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='api_name',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
