# Generated by Django 4.2.23 on 2026-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_categories_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='jdata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='jdata'),
        ),
    ]
