# Generated by Django 4.2.23 on 2026-05-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_datafile_jdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='categories',
            new_name='category',
        ),
    ]
