# Generated by Django 4.2.23 on 2026-05-04 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shop', '0007_rename_categories_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_pay_method', to='shop.payment', verbose_name='Paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='brands', to='shop.brand', verbose_name='brands'),
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('cart', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cart')),
                ('daily', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Daily')),
                ('weekly', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Weekly')),
                ('monthly', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='monthly')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.payment', verbose_name='Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
