# Generated by Django 4.2.23 on 2026-05-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_payment_method_alter_payment_brands_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='cart_products', to='shop.cartproduct', verbose_name='Products'),
        ),
    ]
