# Generated by Django 4.2.23 on 2026-05-04 03:27

import apps.shop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='shop.brand', verbose_name=apps.shop.models.Brand),
        ),
    ]
