# Generated by Django 4.2.23 on 2026-05-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='related_brand_payment', to='shop.brand', verbose_name='brands'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Payoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Payoption Name')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fee_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Fee %')),
                ('fee_fix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Fee Fix')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('svg', models.TextField(blank=True, null=True, verbose_name='Svg')),
                ('html', models.TextField(blank=True, null=True, verbose_name='Html')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payopt_paymeth', to='shop.payment', verbose_name='Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payoptions',
            field=models.ManyToManyField(blank=True, related_name='pay_options', to='shop.payoptions', verbose_name='payoptions'),
        ),
    ]
