# Generated by Django 4.2.23 on 2026-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_payment_extra_data_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regions',
            field=models.JSONField(blank=True, default=None, max_length=255, null=True, verbose_name='Regions'),
        ),
    ]
