# Generated by Django 4.2.23 on 2026-05-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_cart_payment_method_alter_product_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', unique=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='V4VHMySM', max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
