# Generated by Django 4.2.23 on 2026-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_cart_products_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cart_products', to='shop.cartproduct', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='HCjj9175', max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
