# Generated by Django 3.2.13 on 2023-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_cartn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartn',
            name='cproducts',
            field=models.JSONField(blank=True, null=True, verbose_name='cproducts json'),
        ),
    ]
