# Generated by Django 3.2.13 on 2023-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_alter_cart_ex_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='json',
            field=models.JSONField(default=dict, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='order',
            name='json',
            field=models.JSONField(default=dict, verbose_name='json'),
        ),
    ]
