# Generated by Django 3.2.13 on 2023-06-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20230618_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='json'),
        ),
    ]
