# Generated by Django 3.2.13 on 2023-06-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_alter_customer_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
    ]
