# Generated by Django 3.2.13 on 2023-10-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_order_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='json'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='reference',
            field=models.CharField(default='', max_length=555, verbose_name='reference'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
        migrations.AddField(
            model_name='walletorder',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Trash'),
        ),
    ]
