# Generated by Django 3.2.13 on 2023-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_auto_20231002_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginstatistic',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Country Code'),
        ),
    ]
