# Generated by Django 3.2.13 on 2023-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_loginstatistic_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginstatistic',
            name='json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='json'),
        ),
    ]
