# Generated by Django 4.2.7 on 2024-03-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0025_basket_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.basket', verbose_name='Basket')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.customer', verbose_name='Owner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.order', verbose_name='Order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.payment', verbose_name='Payment')),
                ('payoptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.payoptions', verbose_name='Payoptions')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.wallet', verbose_name='Wallet')),
                ('worder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcollection', to='eshop.walletorder', verbose_name='Wallet Owner')),
            ],
        ),
    ]
