# Generated by Django 4.2.7 on 2024-03-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0026_modelcollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelCollection',
        ),
    ]
