# Generated by Django 4.2.7 on 2024-03-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0027_delete_modelcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_products',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='Basket Products'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='fingprint',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='FingerPrint'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='basket', to='eshop.product', verbose_name='Products'),
        ),
    ]
