# Generated by Django 4.2.7 on 2024-03-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0028_alter_basket_basket_products_alter_basket_fingprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.JSONField(default=dict, verbose_name='Currency')),
                ('final_price', models.JSONField(default=dict, verbose_name='Final Price')),
                ('products', models.JSONField(default=dict, verbose_name='Products')),
                ('del_email', models.CharField(blank=True, max_length=55, null=True, verbose_name='Del Email')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending_payment', max_length=100, verbose_name='Order Status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('invoice', models.JSONField(blank=True, default=dict, null=True, verbose_name='Invoice')),
                ('postdata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Postdata')),
                ('responsedata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Response data')),
                ('addinfo', models.JSONField(blank=True, default=dict, null=True, verbose_name='Additional info')),
                ('trash', models.BooleanField(default=False, verbose_name='Trash')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='eshop.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
