# Generated by Django 4.2.7 on 2024-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0031_rename_final_price_orders_total_orders_process_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay_method',
            field=models.JSONField(default=dict, verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pay_options',
            field=models.JSONField(default=dict, verbose_name='Payment options'),
        ),
    ]
