# Generated by Django 4.2.7 on 2024-03-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0034_alter_orders_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='eshop.orders', verbose_name='orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='eshop.basket', verbose_name='Basket'),
        ),
    ]
