# Generated by Django 4.2.7 on 2024-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0036_alter_basket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='history',
            field=models.BinaryField(blank=True, null=True, verbose_name='History'),
        ),
    ]
