# Generated by Django 4.2.7 on 2024-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0037_currency_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='history',
        ),
        migrations.AddField(
            model_name='currency',
            name='histori',
            field=models.BinaryField(blank=True, null=True, verbose_name='Histori'),
        ),
    ]
