# Generated by Django 4.2.23 on 2026-05-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier')),
                ('supplier_code', models.CharField(choices=[('PREPAIDFORGE', 'Prepaidforge')], max_length=50, verbose_name='supplier code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='productcode',
            old_name='suplier_order_id',
            new_name='supplier_order_id',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='suplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suplier_product',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_product',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='supplier_product'),
        ),
        migrations.DeleteModel(
            name='Suplier',
        ),
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_supplier', to='shop.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', to='shop.supplier'),
        ),
    ]
