# Generated by Django 4.2.23 on 2026-05-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=76, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_pay_method', to='shop.payment', verbose_name='Paymentmethod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regions',
            field=models.JSONField(blank=True, default=dict, max_length=255, null=True, verbose_name='Regions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='2glLGuey', max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
