# Generated by Django 4.2.23 on 2026-05-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_cartproduct_product_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product', unique=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product_codes',
            field=models.ManyToManyField(blank=True, related_name='related_cart_productproduct_codes', to='shop.productcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='yRgAqOJI', max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
