# Generated by Django 4.2.23 on 2026-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_products', to='shop.cartproduct', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='HJ4DTdVI', max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
