# Generated by Django 4.2.23 on 2026-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_cart_products_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='wBQ2QNet', max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
