# Generated by Django 4.2.23 on 2026-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='Sku'),
        ),
    ]
