# [program:sinc_dir]
# command=/home/dcback/venv/bin/python3 sinc_dir.py
# directory=/home/dcback/programs
# user=root
# autorestart=true
# redirect_stderr=true
# stdout_logfile=/home/sinc_dir.log


# [supervisord]
# logfile = /home/supervisord.log
# logfile_maxbytes = 50MB
# logfile_backups=10
# loglevel = error
# pidfile = /home/supervisord.pid
# nodaemon = true
# minfds = 1024
# minprocs = 200
# umask = 022
# user = root
# identifier = supervisor_sinc_dir
# directory = /tmp
# nocleanup = false
# childlogdir = /tmp
